### ISSUE TITLE
Aumentar espaço para assinaturas no Termo de Aprovação

### ISSUE THREAD

**Issue by christinaflach** [PGCOMP-UFBA/pgcomp-ufba-latex#28]
Atualmente, com uso frequente de assinatura digital gov.br, precisamos de mais espaço vertical  entre os nomes dos membros da Banca para que caibam as assinaturas, sem ocultar outros elementos do Termo.

Vou tentar fazer. Se não conseguir, peço ajuda aos universitários ;-)

@ibirisol @rodrigorgs

**Comment by christinaflach** [comment]
@ibirisol @rodrigorgs @alopesajr 
Um de vocês poderia revisar a modificação que fiz no arquivo .cls na página do Termo de Aprovação? Coloquei um exemplo de como ficou.
[2023_Exemplo_Termo_assinado.pdf](https://github.com/PGCOMP-UFBA/pgcomp-ufba-latex/files/13731150/2023_Exemplo_Termo_assinado.pdf)

**Comment by rodrigorgs** [comment]
Commit 852094931bb4446d534ef0471024aeaaf24776e2, certo?
Parece bom pra mim.

**Comment by christinaflach** [comment]
Fechando.
